name: Docker Build

on:
  push:
    branches: [ ecnc ]
  pull_request:
    branches: [ ecnc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: sysuecnc
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Docker repository to tag the image with
        repository: sysuecnc/chatwoot
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: docker/Dockerfile
        build_args: BUNDLE_WITHOUT=development:test,EXECJS_RUNTIME=Disabled,RAILS_ENV=production,RAILS_SERVE_STATIC_FILES=true
